### ISSUE TITLE
Loading of Comments

### ISSUE THREAD

**Issue by RachanaBP** [hunterkoppenclevr/mention-input-widget#4]
heyy.. I found a Strange issue.. 
I have a list of comments inside a list view.. 
when i add a new comment initially it comes in Edit mode and then switches to view mode. 

https://user-images.githubusercontent.com/42468929/202382255-508ad6c6-82b8-44c3-b57f-d92cc8639afe.mp4

![image](https://user-images.githubusercontent.com/42468929/202376048-ce13935a-23d3-4c61-b90c-7535773eaa18.png)

**Comment by hunter-koppen** [comment]
Hi Rachana, Thanks again for reporting, ill have a look at it when I have time, maybe today :)

**Comment by hunter-koppen** [comment]
@RachanaBP I think I fixed the problem by loaded the widget as read-only by default until data has been loaded. Let me know if you still have problems after updating the widget to 1.0.2.
